env:
  browser: true
  es6: true
  node: true
  jquery: true
extends:
  - 'plugin:vue/essential'
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules: {
  linebreak-style:
    error,
    windows
}
